<?php
// module/Album/view/album/album/index.phtml:

$title = 'Thống kê thành tích của '.$subject->nameF . ' ' . $subject->nameS;
$this->headTitle($title);
?>

<meta charset='utf-8'>
<div class="container">
    <h3><?php echo $title; ?></h3>
    <hr>
    <table class="table table-hover table-striped ">
        <thead>
        <th>Năm</th>
        <th>Danh hiệu</th>
        <th>Hạng mục</th>
        </thead>
        <tbody>
            <?php foreach ($info as $item): ?>
            <tr>
                <td><?php echo $item->year; ?></td>
                <td><?php echo $item->subAwardName; ?></td>
                <td><?php echo $item->awardName; ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>