<?php
// module/Album/view/album/album/index.phtml:

$title = 'Sửa thông tin danh sách Thi đua - Khen thưởng';
$this->headTitle($title);
?>
<meta charset='utf-8'>
<div class="container">
    <h3><?php echo $title; ?></h3>
    <hr>
</div>
<?php
    $form->setAttribute('action','/commend/add?type='.$type.'&id='.$id);
    $form->prepare();
?>
<?php
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('idCmd'));
?>
<br>
<?php
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('idS'));
?>
<br>
<?php
    echo $this->formRow($form->get('idSubAward'));
?>
<br>
<?php
    echo $this->formRow($form->get('year'));
?>
<br>
<?php
    echo $this->formRow($form->get('submit'));
?>
