<?php
// module/Album/view/album/album/index.phtml:
$title = $type == 1 ? 'Thống kê Thi đua - Khen thưởng Cá nhân' : 'Thống kê Thi đua - Khen thưởng Tập thể';
$this->headTitle($title);
?>

<meta charset='utf-8'>
<div class="container">
    <h3><?php echo $title; ?></h3>
    <hr>
    <table style="margin-bottom: 30px; width: 100%; text-align: right">
        <tr>
            <td style="width:200px; display:inline-block; text-align: right;">
                <a class="btn btn-success"  href="<?php echo $this->url('commend', ['action' => 'add', 'type' => $type]); ?>">Thêm mới</a>
            </td>
        </tr>
    </table>
    <table id="example" class="table table-bordered dt-responsive " cellspacing="0" >
        <thead>
            <tr>
                <th><?php echo $type == 1 ? 'Họ tên' : 'Tập thể' ?></th>
                <th>Danh hiệu</th>
                <th>Danh Mục</th>
                <th>Năm</th>
                <th>Thao tác</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th><?php echo $type == 1 ? 'Họ tên' : 'Tập thể' ?></th>
                <th>Danh hiệu</th>
                <th>Danh Mục</th>
                <th>Năm</th>
                <th>Thao tác</th>
            </tr>
        </tfoot>
        <tbody> 
        </tbody>
    </table>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#example').DataTable({

                "language": {
                    "lengthMenu": "Hiển thị _MENU_ bản ghi/trang",
                    "zeroRecords": "Không có thông tin",
                    "info": "Trang _PAGE_ / _PAGES_",
                    "infoEmpty": "Không có bản ghi nào để hiển thị",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "oPaginate": {
                        "sFirst": "<<", // This is the link to the first page
                        "sPrevious": "<", // This is the link to the previous page
                        "sNext": ">", // This is the link to the next page
                        "sLast": ">>" // This is the link to the last page
                    }
                },
                "ajax": {
                    "url": "/commend/listbytype/".$type,
                    "dataSrc": ""
                },
                "columns": [
                    {"data": getFullName},
                    {"data": "subAwardName"},
                    {"data": "awardName"},
                    {"data": "year"},
                    {"data": getBtn}
                ],
            });

        });
        function getFullName(data, type, dataToSet) {
            return "<a href='/commend/detail/" + data.institute + "?id=" + data.idS + "'>" + data.nameF + " " + data.nameS + "</a>";
        }
        function getBtn(data, type, dataToSet) {
            return "<a class='btn btn-danger' href='/commend/edit?type=" + data.institute + "&id=" + data.idCmd + "'>Sửa</a> | <a class='btn btn-warning' href='/commend/delete?id=" + data.idCmd + "'>Xóa</a>";
        }
    </script>