<?php
// module/Album/view/album/album/index.phtml:

$title = 'Thống kê Thi đua - Khen thưởng';
$this->headTitle($title);
?>

<meta charset='utf-8'>
<div class="container">
    <h3><?php echo $title; ?></h3>
    <hr>
    <p style="text-align: right">
        <a class="btn btn-success"  href="<?php echo $this->url('commend', ['action' => 'add', 'type' => $type]); ?>">Thêm mới</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>Tên cá nhân/Tổ chức</th>
                <th>Hình thức khen thưởng</th>
                <th>Loại khen thưởng</th>
                <th>Đối tượng</th>
                <th>Năm</th>
                <th></th>
            </tr>
        </thead>
        <tbody id = "list"> 
        </tbody>
    </table>
</div>
<script language = "javascript">
    $(document).ready(function () {
        $.ajax({
            url: '/commend/listbytype/'.$type,
            type: 'POST',
            dataType: 'json',
            async: true,
            success: function (data, status) {
                $('#list').html('');
                for (i = 0; i < data.length; i++) {
                    commend = data[i];
                    idvalue = commend['idCmd'];
                    urledit = "/commend/edit/".idvalue;
                    var e = $('<tr><td id = "idCmd" style="display: none"><td id = "nameS"></td><td id = "subAwardName"><td id = "awardName"></td><td id = "institute"></td><td id = "year"></td><td id = "btnedit"></td></tr>');
                    $('#idCmd', e).html(commend['idCmd']);
                    $('#nameS', e).html(commend['nameS']);
                    $('#subAwardName', e).html(commend['subAwardName']);
                    $('#awardName', e).html(commend['awardName']);
                    commend['institute'] == 1 ? $('#institute', e).html('Cá nhân') : $('#institute', e).html('Tập thể');
                    $('#year', e).html(commend['year']);
                    $('#btnedit', e).html("<a class='btn btn-danger' href='/commend/edit?type="+commend['institute']+"&id="+commend['idCmd']+"'>Sửa</a> | <a class='btn btn-warning' href='/commend/delete?id="+commend['idCmd']+"'>Xóa</a>");
                    $('#list').append(e);
                }

            },
            error: function (xhr, textStatus, errorThrown) {
                alert('Ajax request failed.');
            }
        });
    });
</script>