<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
                ->prependFile($this->basePath('js/myjs.js'))
        ?>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a  href="<?=
                    $this->url('commend', [
                        'action' => 'listbytype',
                        'id' => '1',
                    ])
                    ?>">
                        <img class="navbar-brand" src="<?= $this->basePath('img/logo.png') ?>" style="max-height: 300px;" alt="Zend Framework <?= \Commend\Module::VERSION ?>"/>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Kết quả thi đua
                                <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?=
                                    $this->url('commend', [
                                        'action' => 'listbytype',
                                        'id' => '1',
                                    ])
                                    ?>">Cá nhân</a></li>
                                <li><a href="<?=
                                    $this->url('commend', [
                                        'action' => 'listbytype',
                                        'id' => '2',
                                    ])
                                    ?>">Tập thể</a></li>
                            </ul>
                        </li>
                        <li class=""><a href="<?= $this->url('award') ?>">Danh mục</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Danh hiệu
                                <span class="caret"></span></a>

                            <ul class="dropdown-menu">
                                <?php foreach ($this->listSub as $award) { ?>
                                    <li>
                                        <a href="<?=
                                        $this->url('subaward', [
                                            'action' => 'index',
                                            'id' => $award->id,
                                        ])
                                        ?>"><?php echo $award->awardName; ?>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Đối tượng khen thưởng
                                <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?=
                                    $this->url('subject', [
                                        'action' => 'index',
                                        'id' => '1',
                                    ])
                                    ?>">Cá nhân</a></li>
                                <li><a href="<?=
                                    $this->url('subject', [
                                        'action' => 'index',
                                        'id' => '2',
                                    ])
                                    ?>">Tập thể</a></li>
                            </ul>
                        </li>

                        <li class=""><a href="<?= $this->url('auth') ?>">Quản lý người dùng</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="login/logout"><span class="glyphicon glyphicon-log-in"></span> Đăng xuất</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
        </div>
        <div class="container">
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> Quản lý Thi đua - Khen thưởng - CỤC TẦN SỐ VÔ TUYẾN ĐIỆN</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
