<?php
// module/Album/view/album/album/index.phtml:

$title = 'Danh sách danh hiệu thi đua - khen thưởng';
$this->headTitle($title);
?>

<meta charset='utf-8'>
<div class="container">
    <h3><?php echo $title; ?></h3>
    <hr>
    <p style="text-align: right">
        <a class="btn btn-success"  href="<?php echo $this->url('subaward', ['action' => 'add', 'id' => $idAward]); ?>">Thêm mới</a>
    </p>
    <table class = "table"> 
        <thead>
            <tr>
                <th>Danh hiệu</th>
                <th>Danh mục</th>
                <th>Đối tượng</th>
                <th></th>
            </tr>
        </thead>
        <tbody id = "list"> 
        </tbody> 
    </table>
</div>

<script language = "javascript">
    $(document).ready(function () {
        $.ajax({
            url: '/subaward/index/'.$idAward,
            type: 'POST',
            dataType: 'json',
            async: true,
            success: function (data, status) {
                $('#list').html('');
                for (i = 0; i < data.length; i++) {
                    subaward = data[i];
                    idvalue = subaward['id'];
                    urledit = "/subaward/edit/".idvalue;
                    var e = $('<tr><td id = "id" style="display: none"><td id = "name"></td><td id = "awardname"></td><td id = "institute"></td><td id = "btnedit"></td></tr>');
                    $('#id', e).html(subaward['id']);
                    $('#name', e).html(subaward['subAwardName']);
                    $('#awardname', e).html(subaward['awardName']);
                    subaward['institute'] == 1 ? $('#institute', e).html('Cá nhân') : $('#institute', e).html('Tập thể');
                    $('#btnedit', e).html("<a class='btn btn-danger' href='/subaward/edit/"+subaward['id']+"'>Sửa</a> | <a class='btn btn-warning' href='/subaward/delete/"+subaward['id']+"'>Xóa</a>");
                    $('#list').append(e);
                }

            },
            error: function (xhr, textStatus, errorThrown) {
                alert('Ajax request failed.');
            }
        });
    });
</script>