<script
    src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>

<a id = "loadSubject" href = "#">Load book information</a> 
</br> </br> 

<table class = "table" > 
   <tbody id = "list"> 
   </tbody> 
</table>  

<script language = "javascript"> 
$(document).ready(function(){  
      $.ajax({ 
         url:        '/subject/ajax', 
         type:       'POST',  
         dataType:   'json', 
         async:      true, 
         success: function(data, status) { 
            var e = $('<tr><th>id</th><th>name</th><th>type</th></tr>'); 
            $('#list').html(''); 
            $('#list').append(e); 
            
            for(i = 0; i < data.length; i++) { 
               subject = data[i]; 
               var e = $('<tr><td id = "idS"></td><td id = "nameS"></td><td id = "typeS"></td></tr>'); 
               $('#idS', e).html(subject['idS']); 
               $('#nameS', e).html(subject['nameS']); 
               $('#typeS', e).html(subject['typeS']);
               $('#list').append(e); 
            } 
         }, 
         error : function(xhr, textStatus, errorThrown) { 
            alert('Ajax request failed.'); 
         } 
      });  
}); 
</script>