<?php
// module/Album/view/album/album/index.phtml:
$title = $type==1?'Danh sách cá nhân':'Danh sách tập thể';
$this->headTitle($title);
?>

<meta charset='utf-8'>
<div class="container">
    <h3><?php echo $title; ?></h3>
    <hr>
    <p style="text-align: right">
        <a class="btn btn-success"  href="<?php echo '/subject/add?type='.$type ?>">Thêm mới</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th><?php echo $type==1?'Họ tên':'Tập thể'?></th>
                <th>Email</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->paginator as $subject):
                ?>
                <tr>
                    <td><a href="/commend/detail/<?php echo $subject->typeS?>?id=<?php echo $subject->idS?>"><?= $this->escapeHtml($subject->nameF).' '?> <?= $this->escapeHtml($subject->nameS) ?></a></td>
                    <td><?= $this->escapeHtml($subject->email) ?></td>
                    <td><a class="btn btn-danger" href="<?php echo '/subject/edit/'.$subject->typeS.'?id='.$subject->idS?>">Sửa</a>  
                        <a class="btn btn-warning" href="<?php echo '/subject/delete?id='.$subject->idS?>" onclick="if (confirm('Bạn chắc chắn muốn xóa?')) { document.location = this.href; } return false;">Xóa</a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php
    // add at the end of the file after the table
    echo $this->paginationControl(
            // the paginator object
            $this->paginator,
            // the scrolling style
            'sliding',
            // the partial to use to render the control
            'subject/partials/paginator.phtml',
            // the route to link to when a user clicks a control link
            array(
                'type' => $type,
            )
    );
    ?>

</div>