<?php
// module/Album/view/album/album/index.phtml:
$title = 'Danh sách cá nhân/tập thể';
$this->headTitle($title);
?>

<meta charset='utf-8'>
<div class="container">
    <h3><?php echo $title; ?></h3>
    <hr>
    <p style="text-align: right">
        <a class="btn btn-success"  href="<?php echo '/subject/add?type='.$type ?>">Thêm mới</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th><?php echo $type==1?'Họ tên':'Tập thể'?></th>
                <th>Email</th>
                <th>Đối tượng</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->paginator as $subject):
                ?>
                <tr>
                    <td><?= $this->escapeHtml($subject->nameF).' '?> <?= $this->escapeHtml($subject->nameS) ?></td>
                    <td><?= $this->escapeHtml($subject->email) ?></td>
                    <td><?= $this->escapeHtml($subject->typeS) == 1 ? 'Cá nhân' : 'Tập thể' ?></td>
                    <td><a class="btn btn-danger" href="<?php echo '/subject/edit?id='.$subject->idS?>">Sửa</a>  
                        <a class="btn btn-warning" href="<?php echo '/subject/delete?id='.$subject->idS?>">Xóa</a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php
    // add at the end of the file after the table
    echo $this->paginationControl(
            // the paginator object
            $this->paginator,
            // the scrolling style
            'sliding',
            // the partial to use to render the control
            'subject/partials/paginator.phtml',
            // the route to link to when a user clicks a control link
            array(
                'type' => $type,
            )
    );
    ?>

</div>