<?php
// module/Album/view/album/album/index.phtml:

$title = 'Thêm người dùng';
$this->headTitle($title);
?>
<meta charset='utf-8'>
<div class="container">
    <h3><?php echo $title; ?></h3>
    <hr>
</div>

<?php
    $form->setAttribute('action',$this->url('auth',['action'=>'add']));
    $form->prepare();
?>

<?php
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('acc'));
?>
<br>
<?php
    echo $this->formRow($form->get('pass'));
?>
<br>
<?php
    echo $this->formRow($form->get('name'));
?>
<br>
<?php
    echo $this->formRow($form->get('submit'));
    
?>