<?php
// module/Album/view/album/album/index.phtml:

$title = 'Danh sách người dùng';
$this->headTitle($title);


?>
<meta charset='utf-8'>
<div class="container">
    <h3><?php echo $title; ?></h3>
    <hr>
    <p style="text-align: right">
        <a class="btn btn-success"  href="<?php echo $this->url('auth',['action' => 'add']); ?>">Thêm mới</a>
    </p>
    <table class="table">
    <thead>
      <tr>
        <th>Tên đăng nhập</th>
        <th>Tên người dùng</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
        <?php
        foreach ($alluser as $use):
        ?>
      <tr>
          <td><?=$this->escapeHtml($use->acc)  ?></td>
          <td><?=$this->escapeHtml($use->name)  ?></td>
          <td><a class="btn btn-danger" href="<?php echo $this->url('auth',['action' => 'edit', 'acc' => $use->id]);?>">Sửa</a>  
              <a style="display:  <?php echo $use->acc=='admin'?'none':'';  ?>" class="btn btn-warning" href="<?php echo $this->url('auth',['action' => 'delete', 'acc' => $use->id]);?>" onclick='if (confirm("Bạn chắc chắn muốn xóa?")) { document.location = this.href; } return false;'>Xóa</a></td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>